death_chance_label = "Death Chance"
death_chance_range = [0.0, 100.0]
death_chance_value = 1.0
infection_rate_label = "Infection Rate"
infection_rate_range = [0.0, 100.0]
infection_rate_value = 2.0
infection_time_label = "Infection Duration"
infection_time_range = [1.0, 1000.0]
infection_time_value = 15.0
particle_radius_label = "Particle Radius"
particle_radius_range = [0.5, 25.0]
particle_radius_value = 2.0
population_size_label = "Population Size"
population_size_range = [5, 25000]
population_size_value = 10000
particle_velocity_label = "Particle Velocity"
particle_velocity_range = [1.0, 100.0]
particle_velocity_value = 15.0